<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{


	public function searchby($param){
		$qb = $this->createQueryBuilder('a')
		->where('a.name LIKE :param')
		->setParameter('param', '%'. $param . '%');


		return $qb->getQuery()->getResult();
	}


	public function getIds(){
		$ids = $this->createQueryBuilder('a')
		->select('a.id')
		->getQuery()
		->getResult();

		$arr = array();
		$keys = array();

		foreach ($ids as $key => $value) {
			foreach ($value as $val) {
				array_push($arr, $val);
			}
		}
		for ($i=0; $i < 3; $i++) {
			$keys[] = $arr[rand(0, count($arr)-1)];
		}
		return $keys;
	}

	public function getByArray($array){
		$qb = $this->createQueryBuilder('a')
		->where('a.id IN (:ids)')
		->setParameter('ids', $array);

		return $qb->getQuery()->getResult();
	}

	public function findArticles(){
		$qb = $this->createQueryBuilder('a')
		->where('a.typeId != :id')
		->setParameter('id', '1');

		return $qb->getQuery()->getResult();
	}
}
