<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByTitle($title){
		$qb = $this->createQueryBuilder('a')
		->where('a.title LIKE :title')
		->setParameter('title', "%". $title ."%");

		return $qb->getQuery()->getResult();
	}
}
