<?php

namespace UsersBundle\Repository;

/**
 * MailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailsRepository extends \Doctrine\ORM\EntityRepository
{

		public function getMailsAdmin(){
		$qb = $this->createQueryBuilder('m')
		->where("m.usersMails LIKE :mail")
		->setParameter('mail', "%service-client@fly-yoga.ovh%")
		->andWhere('m.available = :boolean')
		->setParameter('boolean', true)
		->orderBy('m.sendAt', 'DESC');
		return $qb->getQuery()->getResult();
	}

		public function getSendedMails(){
		$qb = $this->createQueryBuilder('m')
		->where("m.origin LIKE :mail")
		->setParameter('mail', "service-client@fly-yoga.ovh")
		->orderBy('m.sendAt', 'DESC');
		return $qb->getQuery()->getResult();
	}

		public function getDeletedMails(){
		$qb = $this->createQueryBuilder('m')
		->where("m.origin LIKE :mail")
		->setParameter('mail', "service-client@fly-yoga.ovh")
		->andWhere('m.available = :boolean')
		->setParameter('boolean', false)
		->orderBy('m.sendAt', 'DESC');
		return $qb->getQuery()->getResult();
	}

}
