<?php

namespace CourseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseSubsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseSubsRepository extends EntityRepository
{
}
