<?php

namespace CourseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{

	public function getVisibleCourses(){
		$qb = $this->createQueryBuilder('c')
		->where("c.visibility = true");
		return $qb->getQuery()->getResult();

	}
}
